### ISSUE TITLE
No "Connect" option: BLE HearRate Example

### ISSUE THREAD

**Issue by naveenkaje** [MarceloSalazar/mbed-os-example-ble-HeartRate#1]
I am following the steps described in the README.md on NRF52840_DK. The Heartrate monitor is seen during scanning. However, it does not give a "Connect" Option.
See screenshot attached.

![screenshot_20181204-131052](https://user-images.githubusercontent.com/39923816/49466966-f1603700-f7c6-11e8-96e0-299bd9554646.png)

I also tried altering the adv_pameters ble::adevertising_type_t::CONNECTABLE_UNDIRECTED to adv_pameters ble::adevertising_type_t::CONNECTABLE_DIRECTED. That did not help.

**Comment by adbridge** [comment]
@naveenkaje These issues should be reported against https://github.com/ARMmbed/mbed-os-example-ble or else they will not be seen or mirrored to Jira....

**Comment by naveenkaje** [comment]
@adbridge will report it against mbed-os-example-ble project.

**Comment by naveenkaje** [comment]
Reported https://github.com/ARMmbed/mbed-os-example-ble/issues/198 and hence closing this

**Comment by adbridge** [comment]
@naveenkaje could you do the same for the other one too ? Thanks
